name: Go

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v `go list ./... | grep -v examples` -coverprofile=coverage.txt -covermode=atomic
      
    - name: Coverage
      uses: codecov/codecov-action@v1
      with:
        file:  ./coverage.txt
        flags: unittests
