# Thanks to:
# https://github.com/mvdan/github-actions-golang
on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout package
        uses: actions/checkout@v4
      - name: Test package
        run: |
          go test -v -coverprofile coverage.out -covermode=count ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
