# Thanks to:
# https://github.com/mvdan/github-actions-golang
on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x, 1.16.x]
        platform: [ubuntu-latest, macos-latest]
        #platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout package
        uses: actions/checkout@v2
      - name: Test package
        run: |
          go test -v -coverprofile=coverage.out -covermode=count ./...
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out
